inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.6.4
  TargetRailsVersion: 6.0.0
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'app/javascript/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'lib/tasks/triclops/**/*'
    - 'tmp/**/*'

Layout/IndentHash:
  EnforcedStyle: consistent

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ParameterLists:
  Exclude:
    - 'app/models/concerns/triclops/resource/iiif_info.rb'

RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/BracesAroundHashParameters:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - 'config/initializers/triclops.rb'

Style/RedundantSelf:
  Enabled: false
