inherit_gem:
  rubocul: rubocul_default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.0.3
  TargetRailsVersion: 7.0
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'app/javascript/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'lib/tasks/triclops/**/*'
    - 'tmp/**/*'

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/*'

Metrics/ClassLength:
  Exclude:
    - 'app/models/resource.rb'

Metrics/ParameterLists:
  Exclude:
    - 'app/models/concerns/triclops/resource/iiif_info.rb'

RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - 'config/initializers/triclops.rb'

Style/RedundantSelf:
  Enabled: false
