inherit_gem:
  rubocul: rubocul_default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.2.2
  TargetRailsVersion: 7.0
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'app/javascript/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'lib/tasks/triclops/**/*'
    - 'tmp/**/*'

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'config/environments/*'
    - 'app/models/resource.rb'
    - 'app/controllers/iiif/images_controller.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/models/resource.rb'
    - 'app/controllers/iiif/images_controller.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'config/initializers/**/*'
    - 'app/models/resource.rb'
    - 'app/controllers/iiif/images_controller.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'config/initializers/**/*'
    - 'app/models/resource.rb'
    - 'app/controllers/iiif/images_controller.rb'

Metrics/MethodLength:
  Max: 14
  Exclude:
    - 'config/initializers/**/*'
    - 'app/models/resource.rb'

Metrics/ParameterLists:
  Exclude:
    - 'app/models/concerns/triclops/resource/iiif_info.rb'

RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

Metrics/AbcSize:
  Max: 21
  Exclude:
    - 'config/initializers/**/*'

RSpec/MultipleExpectations:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - 'config/initializers/triclops.rb'

Style/RedundantSelf:
  Enabled: false
