dist: xenial
language: ruby
sudo: false
cache:
  bundler: true
  npm: true
  yarn: true

rvm:
  - 2.6.4

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - NODE_VERSION=10
    - NODE_VERSION=12

services:
  - redis-server

before_install:
  - sudo apt-get -y install libvips libvips-dev libvips-tools
  - "echo 'gem: --no-document' > ~/.gemrc"
  - gem update --system
  - gem install bundler

before_script:
  - vips --version
  - bundle exec rake triclops:setup:config_files
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install -g yarn
  - npm --version
  - yarn install

script: bundle exec rake triclops:ci
