default: &default
  workers:
    '*' : 1
  polling_interval: 5

development:
  <<: *default
  # More frequent polling interval in development environment
  polling_interval: 1

test:
  <<: *default

production:
  <<: *default
  workers:
    '*' : 1
    'high' : 3
    'low,medium' : 1
