development:
  remote_request_api_key: 'changethis'
  access_stats_enabled: false
  run_queued_jobs_inline: true
  raster_cache:
    on_miss: 'error' # ['generate_and_do_not_cache', 'generate_and_cache', 'error']
    directory: <%= Rails.root.join('tmp', 'triclops_development_cache', 'raster') %>
  lock:
    lock_timeout: 10
    retry_delay: 1
    retry_count: 11
  tmp_directory: <%= Rails.root.join('tmp', 'triclops_development_tmp') %>

test:
  remote_request_api_key: 'changethis'
  access_stats_enabled: false
  run_queued_jobs_inline: true
  raster_cache:
    on_miss: 'error' # ['generate_and_do_not_cache', 'generate_and_cache', 'error']
    directory: <%= Rails.root.join('tmp', 'triclops_test_cache', 'raster') %>
  lock:
    lock_timeout: 10
    retry_delay: 1
    retry_count: 11
  tmp_directory: <%= Rails.root.join('tmp', 'triclops_test_tmp') %>
